/**
 * Created with JetBrains PhpStorm.
 * User: xuheng
 * Date: 12-8-8
 * Time: 2:00
 * To change this template use File | Settings | File Templates.
 */
var templates = [
    {
        "pre":"pre0.png",
        'title':lang.blank,
        'preHtml':'<p class="ue_t">&nbsp;ӭʹUEditor</p>',
        "html":'<p class="ue_t">ӭʹUEditor</p>'

    },
    {
        "pre":"pre1.png",
        'title':lang.blog,
        'preHtml':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">Range</span></h1><p style="text-align:center;"><strong class=" ">UEditorο</strong></p><h3><span class=" " style="font-family:Բ">ʲôRange</span></h3><p style="text-indent:2em;">ڡ롱ѡϵĿ⣬ʱֿеĵ۵Эԡ </p><br /><h3><span class=" " style="font-family:Բ">Rangeܸʲô</span></h3><p style="text-indent:2em;">ڡʼѡϣͨӿʽΪѡıѡһۣԷظĵѡıĸʽ</p>',
        "html":'<h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[ĵ]</span></h1><p style="text-align:center;"><strong class="ue_t">[ĵ]</strong></p><h3><span class="ue_t" style="font-family:Բ">[ 1]</span></h3><p class="ue_t"  style="text-indent:2em;">ڡ롱ѡϵĿ⣬ʱֿеĵ۵Эԡ ʹЩҳüҳšб���Լĵ顣 ͼƬͼϵͼҲ뵱ǰĵЭһ¡</p><h3><span class="ue_t" style="font-family:Բ">[ 2]</span></h3><p class="ue_t"  style="text-indent:2em;">ڡʼѡϣͨӿʽΪѡıѡһۣԷظĵѡıĸʽ ʹáʼѡϵؼֱıʽؼѡʹõǰۣʹĳֱָĸʽ </p><h3><span class="ue_t" style="font-family:Բ">[ 3]</span></h3><p class="ue_t">ڡ롱ѡϵĿ⣬ʱֿеĵ۵Эԡ ʹЩҳüҳšб���Լĵ顣 ͼƬͼϵͼҲ뵱ǰĵЭһ¡</p><p class="ue_t"><br /></p>'

    },
    {
        "pre":"pre2.png",
        'title':lang.resume,
        'preHtml':'<h1 label="Title left" name="tl" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;"><span style="color:#e36c09;" class=" ">WEBǰ˿</span></h1><table width="100%" border="1" bordercolor="#95B3D7" style="border-collapse:collapse;"><tbody><tr><td width="100" style="text-align:center;"><p><span style="background-color:transparent;"></span><br /></p><p></p><p></p><p>Ƭ</p></td><td><p><span style="background-color:transparent;"> ϵ绰</span><span class="ue_t" style="background-color:transparent;">[ĵ绰]</span><br /></p><p><span style="background-color:transparent;"> ʼ</span><span class="ue_t" style="background-color:transparent;">[ĵʼַ]</span><br /></p><p><span style="background-color:transparent;"> ͥסַ</span><span class="ue_t" style="background-color:transparent;">[ĵַ]</span><br /></p></td></tr></tbody></table><h3><span style="color:#E36C09;font-size:20px;">Ŀְλ</span></h3><p style="text-indent:2em;" class=" ">WEBǰзʦ</p><h3><span style="color:#e36c09;font-size:20px;">ѧ</span></h3><p><span style="display:none;line-height:0px;" id="_baidu_bookmark_start_26"></span></p><ol style="list-style-type:decimal;"><li><p><span class="ue_t">[ֹʱ]</span> <span class="ue_t">[ѧУ] </span> <span class="ue_t">[ѧרҵ]</span> <span class="ue_t">[ѧλ]</span></p></li></ol><h3><span style="color:#e36c09;font-size:20px;" class="ue_t"></span></h3><p><br /></p>',
        "html":'<h1 label="Title left" name="tl" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;"><span style="color:#e36c09;" class="ue_t">[˴]</span></h1><p><span style="color:#e36c09;"><br /></span></p><table width="100%" border="1" bordercolor="#95B3D7" style="border-collapse:collapse;"><tbody><tr><td width="200" style="text-align:center;" class="ue_t">˴Ƭ</td><td><p><br /></p><p> ϵ绰<span class="ue_t">[ĵ绰]</span></p><p><br /></p><p> ʼ<span class="ue_t">[ĵʼַ]</span></p><p><br /></p><p> ͥסַ<span class="ue_t">[ĵַ]</span></p><p><br /></p></td></tr></tbody></table><h3><span style="color:#e36c09;font-size:20px;">Ŀְλ</span></h3><p style="text-indent:2em;" class="ue_t">[˴ְλ]</p><h3><span style="color:#e36c09;font-size:20px;">ѧ</span></h3><p><span style="display:none;line-height:0px;" id="_baidu_bookmark_start_26"></span></p><ol style="list-style-type:decimal;"><li><p><span class="ue_t">[ֹʱ]</span> <span class="ue_t">[ѧУ] </span> <span class="ue_t">[ѧרҵ]</span> <span class="ue_t">[ѧλ]</span></p></li><li><p><span class="ue_t">[ֹʱ]</span> <span class="ue_t">[ѧУ]</span> <span class="ue_t">[ѧרҵ]</span> <span class="ue_t">[ѧλ]</span></p></li></ol><h3><span style="color:#e36c09;font-size:20px;" class="ue_t"></span></h3><ol style="list-style-type:decimal;"><li><p><span class="ue_t">[ֹʱ]</span> <span class="ue_t">[빫˾]</span> <span class="ue_t">[ְλ]</span> </p></li><ol style="list-style-type:lower-alpha;"><li><p><span class="ue_t">[븺Ŀ]</span> <span class="ue_t">[Ŀ]</span></p></li><li><p><span class="ue_t">[븺Ŀ]</span> <span class="ue_t">[Ŀ]</span></p></li></ol><li><p><span class="ue_t">[ֹʱ]</span> <span class="ue_t">[빫˾]</span> <span class="ue_t">[ְλ]</span> </p></li><ol style="list-style-type:lower-alpha;"><li><p><span class="ue_t">[븺Ŀ]</span> <span class="ue_t">[Ŀ]</span></p></li></ol></ol><p><span style="color:#e36c09;font-size:20px;">ռ</span></p><p style="text-indent:2em;"> &nbsp;<span class="ue_t">[Լյļ]</span><br /></p>'

    },
    {
        "pre":"pre3.png",
        'title':lang.richText,
        'preHtml':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;" class="ue_t">[˴±]</h1><p><img src="http://img.baidu.com/hi/youa/y_0034.gif" width="150" height="100" border="0" hspace="0" vspace="0" style="width:150px;height:100px;float:left;" />ͼĻŷ</p><p>ͼƬΧͼƬŰ</p><p>ǰͼƬþ룬Ȼ󼴿ұ</p><p><br /></p><p><img src="http://img.baidu.com/hi/youa/y_0040.gif" width="100" height="100" border="0" hspace="0" vspace="0" style="width:100px;height:100px;float:right;" /></p><p>ûʲôĻƷʽأǾһ</p><p><br /></p><p>ӭҶೢԣΪUEditorṩģ壡</p>',
        "html":'<p><br /></p><h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;" class="ue_t">[˴±]</h1><p><img src="http://img.baidu.com/hi/youa/y_0034.gif" width="300" height="200" border="0" hspace="0" vspace="0" style="width:300px;height:200px;float:left;" />ͼĻŷ</p><p>1. ͼƬΧͼƬŰ</p><p>ǰͼƬþ룬Ȼ󼴿ұı</p><p><br /></p><p>2. ͼƬңΧͼƬŰ</p><p>ǰͼƬþҶ룬Ȼ󼴿ı</p><p><br /></p><p>3. ͼƬлŰ</p><p>ףûа취</p><p><br /></p><p><br /></p><p><img src="http://img.baidu.com/hi/youa/y_0040.gif" width="300" height="300" border="0" hspace="0" vspace="0" style="width:300px;height:300px;float:right;" /></p><p>ûʲôĻƷʽأǾһ</p><p><br /></p><p>ӭҶೢԣΪUEditorṩģ壡</p><p><br /></p><p>ռλ</p><p><br /></p><p>ռλ</p><p><br /></p><p>ռλ</p><p><br /></p><p>ռλ</p><p><br /></p><p>ռλ</p><p><br /></p><p><br /></p>'
    },
    {
        "pre":"pre4.png",
        'title':lang.sciPapers,
        'preHtml':'<h2 style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;text-align:center;" class="ue_t">[±]</h2><p><strong><span style="font-size:12px;">ժҪ</span></strong><span style="font-size:12px;" class="ue_t">ܳܳܳܳܳܳܳܳܲժҪ</span></p><p style="line-height:1.5em;"><strong> 1</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">ܶݣͼĻţбȡ</span></p><p style="line-height:1.5em;"><strong> 2</strong></p><ol style="list-style-type:lower-alpha;"><li><p class="ue_t">б 1</p></li><li><p class="ue_t">б 2</p></li><ol style="list-style-type:lower-roman;"><li><p class="ue_t">༶б 1</p></li><li><p class="ue_t">༶б 2</p></li></ol><li><p class="ue_t">б 3<br /></p></li></ol><p style="line-height:1.5em;"><strong> 3</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">ͼĻŵ</span></p><p style="text-indent:2em;"><br /></p>',
        'html':'<h2 style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;text-align:center;" class="ue_t">[±]</h2><p><strong><span style="font-size:12px;">ժҪ</span></strong><span style="font-size:12px;" class="ue_t">ܳܳܳܳܳܳܳܳܲժҪ</span></p><p style="line-height:1.5em;"><strong> 1</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">ܶݣͼĻţбȡ</span></p><p style="line-height:1.5em;"><strong> 2</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">б</span></p><ol style="list-style-type:lower-alpha;"><li><p class="ue_t">б 1</p></li><li><p class="ue_t">б 2</p></li><ol style="list-style-type:lower-roman;"><li><p class="ue_t">༶б 1</p></li><li><p class="ue_t">༶б 2</p></li></ol><li><p class="ue_t">б 3<br /></p></li></ol><p style="line-height:1.5em;"><strong> 3</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">ͼĻŵ</span></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">Զ</span></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">ұͼƬ</span></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">ûģҲԿ</span></p><p><br /></p>'
    }
];